name: json_graph_editor
description: A Flutter widget for visualizing and editing JSON as an interactive node graph.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  re_editor: ^0.9.0
  provider: ^6.1.5+1
  re_highlight: ^0.0.3
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
